---
title: "Report_VoserWeber"
output: html_document
---

## 8.1.1 Physical geography and phenology

1. What does the intercept indicate?

The intercept indicates the value of the outcome (DOY) when the predictor (altitude) is zero.

2. How can you interpret the slope?

With higher altitude, the DOY increases (~37 days per 1'000 m of elevation gain), meaning the vegetation greenup is later in the year.

3. How to convert the established relationship with altitude, to one with temperature (Without actually doing it, just describe how you would go about this and what you would expect? Can you approximate the effect of 1 degree of warming?)

Depending on the atmosphere's local water content, air temperature decreases by 0.5 - 1.0 °C per 100 meters of elevation. This relationship could be used to create a model which would predict the change of time in the local vegetation greenup - say the temperature rises by 1 °C (and the atmosphere is dry), then the vegetation greenup would occur ~3.7 days earlier.

## 8.1.2 Temporal and spatial anomalies

For a location near the Adirondacks in the North-Eastern United States (Figure 8.1) gather phenology data on both the day of greenup and the day of maximum canopy development of a location centered on 43.5
N and 74.5
W. Use a product that directly provides these quantities. Gather data for all pixels 100 km around this location for years 2001 to 2010. Ensure you have the right region, e.g. by plotting it terra::plot(your_raster). Similarly, download land cover data for the year 2010 for the same spatial extent, and only consider IGBP broadleaf and mixed forest classes in your analysis.

For the years 2001 - 2009 calculate the long term mean (LTM) and standard deviation (SD) of the phenology metrics. Calculate location with an early greenup for 2010 (< LTM - 1 SD) and locations with late maturity (> LTM + 1 SD).

Describe the observed patterns and speculate about the underlying reasons. In addition, download a digital elevation map for the United States (30s resolution), and compare differences in altitude (e.g. a boxplot) across locations where you do or do not see any patterns in phenology.